# -*- coding: utf-8 -*-
"""src/__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10I6bn3UOFCxZifKk8CO7PtkhA0Ci_e88
"""

# src/__init__.py
# This file makes 'src' a Python package.