# -*- coding: utf-8 -*-
"""src/reverse/__init__.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAeun_QpK5sBKZoHQ1CElhSny8xMwPe3
"""

# src/reverse/__init__.py
# This file makes 'reverse' a Python package.