# -*- coding: utf-8 -*-
"""tests/conftest.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2lHpWtkncZ7EjRAkzYSzipQCJrdCSnw
"""

import os
import sys

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)