# -*- coding: utf-8 -*-
"""File Structure Checker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bS0QeIZtLaqyCXhJKQaHwgrLNdb00lrU
"""

import os
import sys

print("🔍 Verifying 'ReVerse' project file structure...")

# Define the expected directories relative to the project root
required_dirs = [
    'src',
    'src/reverse',
    'src/reverse/templates',
    'src/migrations',
    'tests',
    '.devcontainer'
]

# Define the expected files, with their full paths from the project root
required_files = [
    'src/reverse/main.py',
    'src/reverse/main_enterprise.py',
    'src/reverse/agents.py',
    'src/reverse/config.py',
    'src/reverse/dashboard.py',
    'src/reverse/router.py',
    'src/reverse/shipper.py',
    'src/reverse/compass_cli.py',
    'src/reverse/templates/index.html',
    'src/migrations/0001_update_job_metadata.py',
    'tests/conftest.py',
    'tests/test_agents.py',
    'tests/test_call_external_agent.py',
    'tests/test_get_job_status.py',
    'tests/test_hyperprompt_request.py',
    'tests/test_job_metadata.py',
    'tests/test_process_job.py',
    'Dockerfile',
    'docker-compose.yml',
    'Makefile',
    'requirements.txt',
    '.env.example',
    'README.md',
    '.devcontainer/Dockerfile',
    '.devcontainer/devcontainer.json',
    '.gitignore',
    'push.sh',
]

missing_items = []
found_items = []

print("\nVerifying directories...")
for item in required_dirs:
    if os.path.isdir(item):
        found_items.append(item)
        print(f"✅ Directory found: {item}")
    else:
        missing_items.append(item)
        print(f"❌ Directory MISSING: {item}")

print("\nVerifying files...")
for item in required_files:
    if os.path.isfile(item):
        found_items.append(item)
        print(f"✅ File found: {item}")
    else:
        missing_items.append(item)
        print(f"❌ File MISSING: {item}")

print("\n" + "="*40)
if not missing_items:
    print("✅ Success! Your project structure is correct.")
    sys.exit(0)
else:
    print("❌ Error: Your project structure is incomplete or incorrect.")
    print("\nMissing or misplaced items:")
    for item in missing_items:
        print(f"  - {item}")
    print("Please follow the provided folder solution to fix this.")
    sys.exit(1)