# -*- coding: utf-8 -*-
"""tests/test_job_metadata.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEDFvmu_PcUktI0IP_1STzA4C012qgqd
"""

import pytest

from src.reverse.main_enterprise import Job


def test_jobs_receive_distinct_metadata_dicts():
    job_one = Job(id="job-1", user_id="user", status="pending")
    job_two = Job(id="job-2", user_id="user", status="pending")

    assert job_one.metadata_json == {}
    assert job_two.metadata_json == {}
    assert job_one.metadata_json is not job_two.metadata_json

    job_one.metadata_json["foo"] = "bar"

    assert job_one.metadata_json == {"foo": "bar"}
    assert job_two.metadata_json == {}