# -*- coding: utf-8 -*-
"""tests/test_hyperprompt_request.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIdxv292QX-D6NHZWnm-rlGOu3ku5vwC
"""

from src.reverse.main_enterprise import HyperPromptRequest


def test_hyperprompt_request_metadata_is_not_shared_between_instances():
    first_request = HyperPromptRequest(idea="First idea")
    first_request.metadata["foo"] = "bar"

    second_request = HyperPromptRequest(idea="Second idea")

    assert first_request.metadata == {"foo": "bar"}
    assert second_request.metadata == {}