# -*- coding: utf-8 -*-
"""src/reverse/config.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSU5EW5pPlrr7L5_tVUbzxpwlITNspQh
"""

# config.py
import logging
import sys

def setup_logging():
    """Sets up centralized logging to file and console."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] - %(message)s",
        handlers=[
            logging.FileHandler("system.log", mode='a'),
            logging.StreamHandler(sys.stdout)
        ]
    )