# -*- coding: utf-8 -*-
"""src/reverse/shipper.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GP7_KioXwoDfyAMvcJgkF7DgR0QB9T6
"""

import datetime
import json
import os

LOG_FILE = "ship_log.jsonl"

def daily_ship_check():
    """Logs the daily shipping commitment."""
    print("--- ⚡ Daily Ship Commitment ⚡ ---")

    # Ensure the file exists
    if not os.path.exists(LOG_FILE):
        with open(LOG_FILE, 'w') as f:
            pass # Create empty file

    log = {
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "commitment": input("What ONE thing am I shipping today? > "),
        "blocker": input("What is the main blocker right now? > "),
        "status": "committed" # committed, shipped, learned
    }

    with open(LOG_FILE, "a") as f:
        json.dump(log, f)
        f.write("\n")

    print(f"\n✅ Commitment logged. Ship '{log['commitment']}' by midnight or mark as learning.")
    return log["commitment"]

if __name__ == "__main__":
    target = daily_ship_check()